---
title: "EDS 222 Final Project"
author: "Marie Rivers"
date: "11/13/2021"
output: 
  html_document:
    theme: flatly
    code_folding: show
    toc: TRUE
    toc_float: TRUE
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(skimr)
library(GGally)
library(lubridate)
library(janitor)
library(kableExtra)
library(stringr)
library(ggplot2)
library(patchwork)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggrepel)
library(ggbeeswarm)
library(tidycensus)
```



# Read in EQI data and select columns of interest

```{r}
eqi <- read_csv(here("data", "eqi_data", "Eqi_results_2013JULY22.csv")) %>% 
  select(stfips, county_name, state, air_EQI_22July2013, water_EQI_22July2013, land_EQI_22July2013, sociod_EQI_22July2013, built_EQI_22July2013, EQI_22July2013)
```

# Read in county level population data

```{r}
header <- c("geographic_area", "april_1_2000", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "april_1_2010", "july_1_2010")

codes <- c("01", "02", "04", "05", "06", "08", "09", "10", "11", "12", "13", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "44", "45", "46", "47", "48", "49", "50", "51", "53", "54", "55", "56")
```

```{r}
source(here("src", "state_pop_fun.R"))
```


```{r}
all_states = data.frame()

for (i in seq_along(codes)) {
state <- state_pop_fun(fips = codes[i])
state_df <- data.frame(state)
all_states <- rbind(all_states, state_df)
}
```

