---
title: "Untitled"
author: "Marie Rivers"
date: "11/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
```

```{r}
header <- c("geographic_area", "april_1_2000", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "april_1_2010", "july_1_2010")
```

```{r}
test_files <- list.files(here("data", "population_data", "test_folder"), pattern = "*.csv")
files_df <- data.frame(matrix(unlist(test_files), nrow = length(test_files), byrow = TRUE)) %>% 
  rename(source_file = matrix.unlist.test_files...nrow...length.test_files...byrow...TRUE.)
```


```{r}
files_df$source_file[2]
```

```{r}
test_files %>% 
  map(.f = ~read_csv(.x)) %>% 
  set_names(nm = test_files) %>% 
  map_dfr(identity, .id = "Name")

```


```{r}
test_files2 <- c("co-est00int-01-01.csv", "co-est00int-01-02.csv", "co-est00int-01-04.csv", "co-est00int-01-05.csv")
pop <- vector(length = length(test_files2))
```
```{r}
for (file in test_files2) {
  pop_data <- read_csv(here("data", "population_data", "test_folder", test_files2[file]), skip = 5, col_names = header)
  mutate(pop_data, source = test_files2[[file])
}
```

```{r}
for (file in seq_along(test_files2)) {
  poop_data <- read_csv(here("data", "population_data", "test_folder", test_files2), skip = 5, col_names = header)
  poop_dat[file] <- mutate(poop_data, source = test_files2[file])
}
```

```{r}
pop1 <- read_csv(here("data", "population_data", "test_folder", test_files2[1]), skip = 5, col_names = header) %>% 
  mutate(source = test_files2[1])
```



```{r}
for (file in files_df) {
  pop_data <- mutate(source = files_df[file]) 
}
```

```{r}
def_fun <- function(df) {
  for (i in df) {
    pop <- read_csv(here("data", "population_data", "csv_files", df[[i]]),
                       skip = 5,
                       col_names = header) 
  }
}

```

```{r}
def_fun(df = test_files)
```


for (i in 2:length(time_yr)) {
  proj_year[i,] <- fish_leslie %*% proj_year[i-1,]
}
test_func <-


for (i in 2:length(files_df)) {
  test_data[i,] <- files_df[i]

 %>% 
    mutate(source_file = files_df[i]))
    
```{r}
alabama <- read_csv(here("data", "population_data", "csv_files", "co-est00int-01-01.csv"), skip = 5, col_names = header) %>% 
  filter(april_1_2000 != "na") %>%  
  mutate_at("geographic_area", str_replace, ".", "")
```

```{r}
test_fips <- c("01", "02", "04", "05")

codes <- c("01", "02", "04", "05", "06", "08", "09", "10", "11", "12", "13", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "44", "45", "46", "47", "48", "49", "50", "51", "53", "54", "55", "56")
```

```{r}
state_fun <- function(fips) {
  path = paste0("co-est00int-01-", fips, ".csv")
  state_data <- read_csv(here("data", "population_data", "test_folder", path), skip = 5, col_names = header) %>% 
  mutate(state_fips = fips) %>% 
  filter(april_1_2000 != "na") %>% 
  mutate_at("geographic_area", str_replace, ".", "") %>% 
  relocate(state_fips, .after = geographic_area)
}
```

```{r}
funk <- state_fun(c("01", "02", "04", "05"))
```

```{r}
state_1 <- state_fun(fips = "01")
```

```{r}
source(here("src", "state_pop_fun.R"))
for (i in 1:length(test_fips)){
  xxxx <- state_pop_fun(fips = test_fips[i])
}
#xxx_test_fips[2] <- state_pop_fun(fips = test_fips[2])

```



filter(april_1_2000 != "na") %>%  
  mutate_at("geographic_area", str_replace, ".", "")
